"""Canvas LMS integration.

Canvas uses bearer token authentication with REST API at /api/v1/

Key endpoints:
  GET    /courses - list courses
  GET    /courses/{courseId}/assignments - list assignments
  GET    /courses/{courseId}/assignments/{assignmentId}/submissions - list submissions
  GET    /calendar_events - list calendar events (including due dates)
  GET    /users/{userId}/courses - courses for a user
  POST   /courses/{courseId}/assignments/{assignmentId}/submissions - submit

Requires:
  - Canvas instance URL (e.g., https://canvas.institution.edu)
  - API token (generated by user in Canvas account settings)

Canvas is typically simpler to integrate than Blackboard since it uses
simpler bearer token auth instead of OAuth2.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
import logging

from scholarr.core.integrations import BaseIntegrationProvider, IntegrationType, IntegrationStatus

logger = logging.getLogger(__name__)


class CanvasProvider(BaseIntegrationProvider):
    """Canvas LMS integration provider.

    Simpler than Blackboard - uses bearer token auth and consistent REST API.
    """

    def __init__(self):
        """Initialize Canvas provider."""
        super().__init__("canvas", IntegrationType.LMS)
        self._api_token: Optional[str] = None
        self._user_id: Optional[int] = None

    async def connect(self, config: Dict[str, Any]) -> bool:
        """Connect to Canvas instance.

        Config should contain:
            canvas_url: Base URL of Canvas instance (e.g., https://canvas.institution.edu)
            access_token: API token from user's Canvas account settings

        Args:
            config: Connection configuration dictionary

        Returns:
            True if connection successful
        """
        try:
            required = ["canvas_url", "access_token"]
            if not all(key in config for key in required):
                missing = [k for k in required if k not in config]
                raise ValueError(f"Missing required config: {missing}")

            self._config = config
            self._api_token = config.get("access_token")

            # Test connection
            success = await self.test_connection()
            if success:
                self._is_connected = True
                self._clear_last_error()
                logger.info(f"Connected to Canvas at {config.get('canvas_url')}")
            else:
                self._set_last_error("Failed to authenticate with Canvas")

            return success

        except Exception as e:
            self._set_last_error(str(e))
            logger.error(f"Canvas connection error: {e}")
            return False

    async def disconnect(self) -> bool:
        """Disconnect from Canvas.

        Returns:
            True if successful
        """
        try:
            self._is_connected = False
            self._api_token = None
            self._clear_last_error()
            logger.info("Disconnected from Canvas")
            return True
        except Exception as e:
            self._set_last_error(str(e))
            return False

    async def test_connection(self) -> bool:
        """Test if API token is valid by fetching user profile.

        Calls GET /users/self

        Returns:
            True if connection test successful
        """
        if not self._api_token:
            return False

        logger.debug("Canvas test_connection: stub implementation")
        return True

    async def get_courses(self) -> List[Dict[str, Any]]:
        """Fetch list of courses for authenticated user.

        Calls GET /courses with enrollment status 'active'

        Returns:
            List of course dictionaries
        """
        logger.debug("Canvas get_courses: stub implementation")
        return []

    async def get_assignments(self, course_id: int) -> List[Dict[str, Any]]:
        """Fetch assignments for a course.

        Calls GET /courses/{courseId}/assignments

        Args:
            course_id: Canvas course ID

        Returns:
            List of assignment dictionaries
        """
        logger.debug(f"Canvas get_assignments for course {course_id}: stub")
        return []

    async def get_submissions(
        self,
        course_id: int,
        assignment_id: int
    ) -> List[Dict[str, Any]]:
        """Fetch submissions for an assignment.

        Calls GET /courses/{courseId}/assignments/{assignmentId}/submissions

        Args:
            course_id: Canvas course ID
            assignment_id: Canvas assignment ID

        Returns:
            List of submission objects for authenticated user
        """
        logger.debug(f"Canvas get_submissions for assignment {assignment_id}: stub")
        return []

    async def get_calendar_events(self) -> List[Dict[str, Any]]:
        """Fetch calendar events (due dates, events, deadlines).

        Calls GET /calendar_events with filters

        Returns:
            List of calendar event dictionaries
        """
        logger.debug("Canvas get_calendar_events: stub")
        return []

    async def submit_assignment(
        self,
        course_id: int,
        assignment_id: int,
        submission_type: str,
        content: Dict[str, Any]
    ) -> bool:
        """Submit an assignment.

        Supports different submission types: online_text_entry, online_upload, etc.

        Args:
            course_id: Canvas course ID
            assignment_id: Canvas assignment ID
            submission_type: Type of submission (text_entry, file_upload, etc.)
            content: Submission content (text or file info)

        Returns:
            True if submission successful
        """
        logger.debug(f"Canvas submit_assignment {assignment_id}: stub")
        return False

    async def sync(self) -> Dict[str, Any]:
        """Sync all data from Canvas.

        Fetches courses, assignments, submissions, and calendar events.

        Returns:
            Dictionary with synced data and any errors
        """
        if not self._is_connected:
            return {"error": "Not connected to Canvas"}

        try:
            results = {
                "courses": [],
                "assignments": [],
                "submissions": [],
                "calendar_events": [],
                "errors": []
            }

            # Sync courses
            courses = await self.get_courses()
            results["courses"] = courses

            # Sync assignments and submissions for each course
            for course in courses:
                course_id = course["id"]
                try:
                    assignments = await self.get_assignments(course_id)
                    results["assignments"].extend(assignments)

                    for assignment in assignments:
                        try:
                            submissions = await self.get_submissions(course_id, assignment["id"])
                            results["submissions"].extend(submissions)
                        except Exception as e:
                            results["errors"].append(
                                f"Failed to sync submissions for assignment {assignment.get('name')}: {e}"
                            )
                except Exception as e:
                    results["errors"].append(
                        f"Failed to sync assignments for course {course.get('name')}: {e}"
                    )

            # Sync calendar events
            try:
                events = await self.get_calendar_events()
                results["calendar_events"] = events
            except Exception as e:
                results["errors"].append(f"Failed to sync calendar events: {e}")

            self._last_sync = datetime.now()
            return results

        except Exception as e:
            self._set_last_error(str(e))
            return {"error": str(e)}

    async def get_status(self) -> IntegrationStatus:
        """Get current status of Canvas integration.

        Returns:
            IntegrationStatus with connection and sync info
        """
        return IntegrationStatus(
            provider_name="canvas",
            provider_type=IntegrationType.LMS,
            is_connected=self._is_connected,
            last_sync=self._last_sync,
            last_error=self._last_error,
            configuration_valid=bool(self._config),
            metadata={
                "canvas_url": self._config.get("canvas_url", "not set"),
                "user_id": self._user_id or "unknown"
            }
        )